name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Resolve package dependencies
      run: xcodebuild -resolvePackageDependencies
      run: git submodule update --init --recursive
   
    - name: Clear cache
      run: rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache
    
    - name: Build app
      run: xcodebuild CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=14.4 -project Socialify.xcodeproj -scheme Socialify clean build
