name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/checkout@v2
    - name: Show Xcode versions
      run: ls -n /Applications/ | grep Xcode*
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13_beta.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Resolve package dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Clear cache
      run: rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache
    
    - name: Build app
      run: xcodebuild CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=14.4 -project Socialify.xcodeproj -scheme Socialify clean build
